source 'http://rubygems.org'
gem 'bundler'
gem 'sequel'
gem 'sinatra'
gem 'rack'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'rdiscount'
gem 'heroku'